export const UserStore = (state:any) => state.user
export const LightSensorStore = (state:any) => state.lightSensor
export const TemperatureSensorStore = (state:any) => state.temperatureSensor
export const FanDeviceStore = (state:any) => state.fanDevice
export const MenuStore = (state:any) => state.menu
export const ResponsiveStore = (state:any) => state.responsive
export const OrderModalStore = (state:any) => state.orderModal
export const SmallNotificationStore = (state:any) => state.smallNotificationModal
export const LogsStore = (state:any) => state.logs
export const CustomersStore = (state:any) => state.customers
export const ParkingSlotsStore = (state:any) => state.parkingSlots
export const AiStore = (state:any) => state.ai
export const StatisticsStore = (state:any) => state.statistics
